Initial approach
Wolox/graphql-inspector-wolox-node pull request #1
Opened 2019-10-15 18:53 UTC by lnmedrano

## Summary
- Compare schema in pre-commit

2019-10-15 19:22 UTC, picollomartin requested changes
Amazing job 🎉 , some comments and two missing things: 
- Changelog of versions
- package-lock.json

2019-10-15 19:22 UTC, mpicollo-wolox commented on README.md
> +  * .js file that exports a GraphQLType variable named schema.
Some things here:
- Add MIT license 
- How contribute to this
- Some instructions for local running
- Mention Wolox as author and maintainer

2019-10-15 19:22 UTC, mpicollo-wolox commented on schema-inspector.js
> +    if (changes.some(c => c.criticality.level === breaking)) {
Add some flag for bypass breaking changes in schema (like level)

2019-10-15 19:22 UTC, mpicollo-wolox commented on package.json
> +  "version": "0.1",
Use semantic version here,`1.0.0` for initial version

2019-10-15 19:22 UTC, mpicollo-wolox commented on package.json
> +  "author": "",
author is `Wolox` check other packages

2019-10-15 19:22 UTC, mpicollo-wolox commented on schema-inspector.js
> +#!/usr/bin/env node
Normally packages use an index like this
```
module.exports = require('./lib')
```
Lib directory contains source code and exports in an index file

2019-11-04 17:05 UTC, ghost requested changes

2019-11-04 17:05 UTC, picollomartin commented on lib/index.js
> +    changes = getChangesInSchema(oldSchemaFile, newSchema);
You could use const in changes and do here something like `changes.push(...getChangesInSchema(oldSchemaFile, newSchema))`

2019-11-08 13:50 UTC, mpuricawolox submitted a review, later dismissed

2019-11-12 19:58 UTC, picollomartin submitted a review, later dismissed

2019-11-14 13:21 UTC, mpuricawolox approved these changes

2019-11-14 13:28 UTC, merged